### ISSUE TITLE
Latest commit causing ProjectRed backpack issues?

### ISSUE THREAD

**Issue by WesTroy** [MrTJP/MrTJPCore#11]
*(First time posting - thanks for the great work you do - we all love PR)*
Using latest (MrTJPCore-1.1.0.30).
Attempting to shift-click items from inventory into ProjectRed backpacks crashes clients with:
[partial log](http://www.hastebin.com/eyavidujiv.avrasm)
Dropping back to 1.1.0.29 fixes the issue. Probably related to the Slot changes in latest commit?

**Comment by MrTJP** [comment]
This was hotfixed. Redownload MrTJPCore.
