### ISSUE TITLE
MRTJP Core causes Twilight Forest Crash

### ISSUE THREAD

**Issue by Zilacon** [MrTJP/MrTJPCore#12]
http://prntscr.com/86wabd

I tried to reproduce this without mrtjpcore mod and it did not crash at all. Basically whenever you enter an area that has a twilight forest biome that has not generated yet this happens.

A fix for this would be nice, thanks.

**Comment by brucethemoose** [comment]
Just got this same crash on a server, twice:

http://pastebin.com/WBNaJcaU

**Comment by covers1624** [comment]
Closing because this is ancient, Also this appears to be MrTJPCore inadvertently causing chunks that don't exist to load and generate around a block the tick handler was watching.

**Comment by Zilacon** [comment]
Took 3 years for you to reply, only to give no solutions.
**(slow clap)**

**Comment by covers1624** [comment]
Tj was busy with large amounts of university work, by the time i was around to help it was the 1.10 port, and 1.7 wasn't supported anymore. There is a solution, don't use 1.7 anymore.
