### ISSUE TITLE
Spam error find in my log when i created a new world

### ISSUE THREAD

**Issue by quienti** [MrTJP/MrTJPCore#14]
http://pastebin.com/XWDqzm29

MrTJPCoreMod{1.1.0.31} [MrTJPCore](MrTJPCore-1.7.10-1.1.0.31-universal.jar) 
ProjRed|Core{4.7.0pre9.92} [ProjectRed Core](ProjectRed-Base.jar) 
ProjRed|Exploration{4.7.0pre9.92} [ProjectRed Exploration]
ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission](ProjectRed-Integration.jar) 
ProjRed|Transportation{4.7.0pre9.92} [ProjectRed Transportation](ProjectRed-Mechanical.jar) 
ProjRed|Compatibility{4.7.0pre9.92} [ProjectRed Compatibility](ProjectRed-Compat.jar) 
ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration](ProjectRed-Integration.jar) 
ProjRed|Fabrication{4.7.0pre9.92} [ProjectRed Fabrication](ProjectRed-Fabrication.jar) 
ProjRed|Illumination{4.7.0pre9.92} [ProjectRed Illumination](ProjectRed-Lighting.jar) 
ProjRed|Expansion{4.7.0pre9.92} [ProjectRed Expansion](ProjectRed-Mechanical.jar) 
ForgeRelocation{0.0.1.4} [ForgeRelocation](ForgeRelocation-0.0.1.4-universal.jar)

**Comment by covers1624** [comment]
1.7 issue, not supported, this is ancient.
