### ISSUE TITLE
MrTJPCore Retrogen enables itself

### ISSUE THREAD

**Issue by Master0r0** [MrTJP/MrTJPCore#15]
I keep having an issue where I can go a week without any issues and then for some reason MrTJPCore enables its retrogen function for some reason even setting the config option to true, tends to happen most commonly when I enable retrogen for another mod

**Comment by covers1624** [comment]
Probably due to user error, not properly saving the file or something perhaps. Regardless, issue occurred on ancient versions, if the issue happens again ever, open a new issue.
