### ISSUE TITLE
Server Crashing in startup

### ISSUE THREAD

**Issue by BobbyMcJoe** [MrTJP/MrTJPCore#17]
I have forge .1448 on my 1.7.10 server. Once I put in MrTJP core it crashes. I tried removing everything else and the problem persists. I would give you the crash log but it doesn't get that far. I am using MrTJPCore-1.1.0.31-universal with Java 7. It isn't RAM, I gave it 4gb.

**Comment by covers1624** [comment]
No log was provided, 1.7 is not supported, this is ancient.
