### ISSUE TITLE
Crash when Generating New Chunks in a World

### ISSUE THREAD

**Issue by Wealthyturtle** [MrTJP/MrTJPCore#20]
Crash when Generating New Chunks in a World.
(Note: This May Not be MrTJPCore's Fault, but it was Referenced in the Crash Report. This May be Caused by Realistic Terrain Generation / Mekanism)

Crash Report:
http://pastebin.com/4JsJKAY1

Issue in Mekanism's Issues: https://github.com/aidancbrady/Mekanism/issues/3975
Issue in Realistic Terrain Generation's Issues: https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/1049

**Comment by covers1624** [comment]
1.7 is ancient, was likely tjcore accidentally generating chunks when it shouldn't have.
