### ISSUE TITLE
Getting console spam on a server

### ISSUE THREAD

**Issue by DeGariless** [MrTJP/MrTJPCore#22]
http://i.imgur.com/qjk8LJD.png

MC: 1.10.2
MrTJPCore: 1.10.2-2.0.0.14
Forge: 2254
Modpack [Unabridged](https://minecraft.curseforge.com/projects/unabridged) Alpha 7

**Comment by DeGariless** [comment]
https://github.com/elytra/Unabridged/issues/600

**Comment by DeGariless** [comment]
Seems like it happens when blocks are either broken or placed or both. not sure.

**Comment by covers1624** [comment]
Fairly sure this was the keytracker having issues, i think its fixed in 1.12, if it happens again open a new issue.
