### ISSUE TITLE
mrtjp.relocation Server Crash

### ISSUE THREAD

**Issue by gmnovakrc** [MrTJP/MrTJPCore#39]
Yes I'm aware there's a lot of mods.
Didn't start crashing until I added these last mods, however if I delete all of these recent added mods and their configs the problem persists. Any help is greatly appreciated.

[Potential conflicting mods.txt](https://github.com/MrTJP/MrTJPCore/files/5759370/Potential.conflicting.mods.txt)

[crash-2021-01-01_14.48.51-client.txt](https://github.com/MrTJP/MrTJPCore/files/5759360/crash-2021-01-01_14.48.51-client.txt)

**Comment by covers1624** [comment]
1.7.10 is not supported anymore. If you can reproduce the issue when 1.15/1.16 builds are released, fantastic.
