### ISSUE TITLE
MrTJPCore causing cascading worldgen lag [1.12.2-2.1.4.43]

### ISSUE THREAD

**Issue by ghost** [MrTJP/MrTJPCore#43]
I'm having issues in logs when using your mod. Console is spaming me this "MrTJPCore causing cascading worldgen lag, lease report this to the mod's issue tracker".

Here is link for pastebin: https://pastebin.com/T7tUrfVG , if you will need full log I can pastebin that too.

Thanks so much for amazing work :)

**Comment by covers1624** [comment]
This is not a bug, volcanoes are big. You can disable Forge's warning for this in the forge config file.
