### ISSUE TITLE
Add a check for updates flag

### ISSUE THREAD

**Issue by CommYutzy** [MrTJP/MrTJPCore#5]
Currently the only update checker option in the config is whether or not to consider unstable builds. It would be nice if we could turn the update checker off all together (I do mass wave updates for my server and don't want users spammed by mod update messages everytime they login)

**Comment by MrTJP** [comment]
Oh? You must've missed the option in the configs... But now that you mentioned it i added one to MrTJPCore.

**Comment by xJon** [comment]
Hey! I just wanted to suggest the same option. As a modpack builder, updates should be my issue, not my players's issue.
Also the latest version does not support the latest version of ProjectRed, so I need to choose between using a stable version or having my players think that some mods are outdated.
Where did you add one?
Thanks.

**Comment by MrTJP** [comment]
Added it just now, its not released yet.  But I can't do anything about that, you'll have to deal with it until a stable version of PR comes out that works with the newer MrTJPCore.

**Comment by xJon** [comment]
Understandable. Thanks for the quick reply

**Comment by Watchful1** [comment]
@MrTJP would you consider changing the recommended MrTJPCore back to 1.0.3 until a new stable ProjectRed comes out? We at FTB are going to be releasing a new pack within the next few days and as it stands every user will get the lengthy update message. We're talking tens if not hundreds of thousands of users.
