### ISSUE TITLE
Version checker doesn't obay config option.

### ISSUE THREAD

**Issue by TOLoneWolf** [MrTJP/MrTJPCore#7]
Not a big issue but even with the update checker set to false it still informs the user there is an update and spams the chat window on first world load.

cfg lines:
general {
    # Flag to set if the update checker should consider unstable builds as a new version.
    B:check_unstable=false

    # Flag to enable or disable the update checker.
    B:check_versions=false
}

**Comment by MrTJP** [comment]
Version checking on MrTJPCore has been removed.
