### ISSUE TITLE
Localize version checker

### ISSUE THREAD

**Issue by Adaptivity** [MrTJP/MrTJPCore#8]
https://github.com/MrTJP/MrTJPCore/blob/59e62ea87e6b347eca6cca4a917c7ad97d612da6/src/mrtjp/core/data/UpdateChecker.scala#L118 this should be localizable.

**Comment by Adaptivity** [comment]
@MrTJP anyword?

**Comment by Adaptivity** [comment]
yet another bump

**Comment by MrTJP** [comment]
Sorry, wasn't following this repo until recently. And I guess I can do this, if you want to bother localizing the single word 'available'. 

As of last version, the only thing the version checker reports is 'mod-name vX.X.X available'.

**Comment by Adaptivity** [comment]
It should be possible to localize "Version %s tag (will be replaced with version number) of %s tag (will be replaced with mod name) is available. Changes:". %s tags will not be localized, word *Changes* should be localized but actual changes should stay in English.

**Comment by Adaptivity** [comment]
So, can you make message 'mod-name vX.X.X available' localizable?

**Comment by covers1624** [comment]
The UpdateChecker will be removed and replaced by using Forge's system. I have a few things i need to follow up with CB's web server backend first to make it happen.
